/*
 * EP0044_PentagonNumbers.cpp
 *
 *  Created on: 14/03/2016
 *      Author: terentz
 *
 * Description:
 Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */

#include "EP0044_PentagonNumbers.hpp"
#include "EulerUtils.hpp"
#include <iostream>

using std::cout;
using std::endl;

/* NAMESPACE DEFINES */
//#define CONST val


/* FUNCTIONS */

void PentagonNumbers::run () {

	/* LOCAL DECLARATIONS */


	/* TEST */


	/* DO THE WORK! */


	/* DISPLAY RESULTS */

	cout << endl;

}


