/*
 * EP0045_TriangPentagHexag.cpp
 *
 *  Created on: 14/03/2016
 *      Author: terentz
 *
 * Description:
 Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */

#include "EP0045_TriangPentagHexag.hpp"
#include "EulerUtils.hpp"
#include <iostream>

using std::cout;
using std::endl;

/* NAMESPACE DEFINES */
//#define CONST val


/* FUNCTIONS */

void TriangPentagHexag::run () {

	/* LOCAL DECLARATIONS */


	/* TEST */


	/* DO THE WORK! */


	/* DISPLAY RESULTS */

	cout << endl;

}


